# Not For Production
services:
  api-server:
    build: .
    image: api-server
    container_name:
    env_file:
      - ./.env
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - task-management

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-management

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.redis/data:/root/redis
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=abc123
      - REDIS_PORT=6379
    networks:
      - task-management

  volumes:
    mysql-data:

  networks:
    api-gateway:
      driver: bridge
