# Not For Production
services:
  api-server:
    build: .
    image: api-server
    container_name: api-server
    env_file:
      - ./.env
    ports:
      - 3000:3000
    restart: unless-stopped

  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.redis/data:/root/redis
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=abc123
      - REDIS_PORT=6379

volumes:
  mysql-data:
    driver: local
# networks:
#   task-management:
#     driver: bridge
